[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.3"
uefi = { version = "0.16", features = ["logger", "alloc", "exts"] }
